### ISSUE TITLE
Typo : can't activate SSL with own certificates.

### ISSUE THREAD

**Issue by cdrcnm** [osixia/docker-phpLDAPadmin#1]
There is an error in image/service/phpldapadmin/assets/apache2/phpldapadmin-ssl.conf
On the line for the CA certificate, the final "}" is missing.
# SSLCACertificateFile /osixia/phpldapadmin/apache2/ssl/${SSL_CA_CRT_FILENAME

and apache2 won't start with this error.

The problem seems to be the same with the image on the docker registry.

**Comment by osixia** [comment]
Yes exactly,
adding "}" at the end should solve these issue. I'll try that and push a fix soon.

Thanks
