### ISSUE TITLE
Cannot start container with iptables error

### ISSUE THREAD

**Issue by filamoon** [osixia/docker-phpLDAPadmin#10]
Error response from daemon: Cannot start container fa7fb0fdb81cef2d79d36579190f5c4ec1b4e8793a97714ab060934eae519aa6: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 192.168.42.6 --dport 443 -j ACCEPT: iptables: No chain/target/match by that name.

Please help...

**Comment by osixia** [comment]
I don't think this error is related to this image it's seems to be a docker daemon pb

**Comment by rudyzhou2** [comment]
looks like a docker daemon bug where the rules regarding docker in iptables mysteriously disappear. Restarting the docker daemon will fix the issue as a work-around as the rules will be reapplied in iptables.
