### ISSUE TITLE
Respect X-Forwarded-Proto header

### ISSUE THREAD

**Issue by IlyaSemenov** [osixia/docker-phpLDAPadmin#19]
Consider a typical setup on docker farm:

Remote user > (HTTPS) > nginx frontend at docker host > (HTTP) > docker container.

This is a perfectly secure setup (unencrypted traffic never hits the physical network), however phpLDAPAdmin will generate a warning: "This web connection is unencrypted."

phpLDAPAdmin docker image must respect X-Forwarded-Proto and disable the warning if the header is set to "https".

**Comment by osixia** [comment]
Thanks i didn't known that :)
can you provide the apache configuration and i make a fix ? (or make a pull request ?)
