### ISSUE TITLE
Problem with adding own config.php

### ISSUE THREAD

**Issue by paulz1** [osixia/docker-phpLDAPadmin#20]
I try to add my own config.php to phpldapadmin container just as explained on GitHub page : 

> Link your config file at run time to /container/service/phpldapadmin/assets/config.php : 
> docker run --volume /data/my-config.php:/container/service/phpldapadmin/assets/config.php --detach osixia/phpldapadmin:0.6.8

But the container doesn't start at all....

a) trying to replace "--volume" to "-v" change nothing;

b) I add "-D" option to docker and "--loglevel debug" option to container. It stops here : 

> Enabling site phpldapadmin.
> Bootstap phpLDAPadmin...
> tr: write error: Broken pipe
> tr: write error
> sed: cannot rename /container/service/phpldapadmin/assets/sedICYBNx: Device or resource busy
> **\* /container/run/startup/phpldapadmin failed with status 4

c) just for information, if I remove "--volume" option the messages 

> tr: write error: Broken pipe
> tr: write error

are still present, but container do start.

I use 

```
>docker -v
Docker version 1.11.0, build 4dc5990
```

on ubuntu 14.04

Thanks for your help

**Comment by osixia** [comment]
Hello,
the tr write error are "normal" :) 

for the config.php file problem have you tried what is described in "Fix docker mounted file problems" on the readme ?

**Comment by paulz1** [comment]
Ok. My fault... I should read all of "Beginner Guide" not only beggining.

`--copy-service` solved problem at once.

Thank you very-very much.

**Comment by osixia** [comment]
great, you're welcome
