### ISSUE TITLE
What's the default username and password to the login?

### ISSUE THREAD

**Issue by hwongcom** [osixia/docker-phpLDAPadmin#6]
How do i use ldap? i'm new and what's the default username and password to the login?

**Comment by osixia** [comment]
There is no default username and password. This container runs only phpLDAPadmin that let you administer an existing ldap server, the ldap server to administer can be set by -e LDAP_HOSTS=ldap.example.com for example.

Then use a username and password of ldap.example.com ldap server.

If you want to create a new ldap server for testing rapidly : 
please refer to https://github.com/osixia/docker-openldap 

Obviously this is not an issue so i'm closing it.

**Comment by hwongcom** [comment]
Hi there, great work on ldap php admin and the server docker, i've spent a week on installation and i've finally made both docker images run on the same server (slow downloads etc)

the issue/problem i'm having with is.. i dont know how to make them both work together. can u pls provide a simplistic tutorial on installation on both servers and how to integrate and use them together?

the problem i have with phpldapadmin is that "Unable to connect to LDAP server 172.17.0.3" when i try to link it to the container for ldap server

I hope you can provide example...

i have done...
docker run -d -p 389:389 -p 389:389/udp -p 636:636 -p 3268:3268/udp -p 3268:3268 -p 3269:3269 -e LDAP_ORGANISATION="Example" -e LDAP_DOMAIN="ldap.example.com" -e LDAP_ADMIN_PASSWORD='testing' osixia/openldap

docker run -p 443:443 -h ldapadmin --name ldapadmin  -e LDAP_HOSTS=172.17.0.3 -d osixia/phpldapadmin

172.17.0.3 is the ldap.example.com's container's internal ip... i'm not sure how to integrate them together...

when i did... https://ldapadmin.example.com/ <- i've edited /etc/hosts to be 127.0.0.1 ldapadmin.example.com

it shows the screen for phpldapadmin, when i input username : admin, password : admin, i get
Unable to connect to LDAP server 172.17.0.3
Error: Invalid DN syntax (34) for user
error   Failed to Authenticate to server
Invalid Username or Password.

please help with how to integrate or set up an example to fuse them together...

another unrelated question... windfisch/phpldapadmin mentioned it fixed the ssl issue and password hash issue... https://registry.hub.docker.com/u/windfisch/phpldapadmin/
is it addressed in yours as well?

Appreciate the help.
