### ISSUE TITLE
LDAP host configuration ignored

### ISSUE THREAD

**Issue by hannes-brt** [osixia/docker-phpLDAPadmin#8]
I've been trying to configure my LDAP host every way imaginable - using both the PHPLDAPADMIN_LDAP_HOSTS environment variable and editing the env.yaml file and building a new image. But in both cases, the phpLDAPadmin interface still shows the ldap.example.org servers in the dropdown list instead of the server I configured.

I also checked the /var/www/phpldapadmin/config/config.php file which only shows the example servers too:

```
/*                                                                              
 * Autogenerated servers variables will come here                               
 */                                                                             
$servers->newServer('ldap_pla');                                                
$servers->setValue('server','name','ldap.example.org');                         
$servers->setValue('server','host','ldap.example.org');                         
$servers->setValue('server','tls',true);                                        
$servers->setValue('login','bind_id','cn=admin,dc=example,dc=org');             
$servers->newServer('ldap_pla');                                                
$servers->setValue('server','name','ldap2.example.org');                        
$servers->setValue('server','host','ldap2.example.org');                        
$servers->newServer('ldap_pla');                                                
$servers->setValue('server','name','ldap3.example.org');                        
$servers->setValue('server','host','ldap3.example.org');                        
```

Do you know why the config file doesn't pick up the servers from the configuration?

**Comment by osixia** [comment]
Can you provide a full example of what you are doing ?
Please list running containers. 

Quick running example on your local computer try : 
sudo docker run -p 443:443 -e PHPLDAPADMIN_LDAP_HOSTS=pop.com -d osixia/phpldapadmin

then go to https://localhost 
you should see pop.com as ldap host

change PHPLDAPADMIN_LDAP_HOSTS to your ldap host
